### ISSUE TITLE
Implement `markdown-it-kbd`?

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow-net#4]
Node modules are way outta my experience, so I don't know how feasible this is, but I would like it if the `markdown-it` plugin for keyboard key rendering [@gerhobbelt/markdown-it-kbd](https://www.npmjs.com/package/@gerhobbelt/markdown-it-kbd) could be included.

For writing documentation, it can be nice to have keyboard rendering of markdown, like how GitHub does:

<kbd>Key</kbd>

<kbd>Enter</kbd>

There are some other parts of the docs I'd like to add to beyond keyboard shortcuts, and it would be a nice feature.

**Comment by vassbo** [comment]
The package you linked does not add it's own styling, it just replaces [[Key]] with <kbd>Key</kbd>. But I just added my own Svelte implementation. I have pushed the changes to the main build.

To use it you have to import the key prop (under the title and description):
```
<script>
import Key from '../../../components/Key.svelte';
</script>
```
Then you can use the component anywhere inside that markdown file:
<Key>KEY</Key>
